blueprint:
  name: Klimaanlage - Föhn-Steuerung (Final & Fixed)
  description: Fixer Offset zur Wunschtemp und 3-stufige Föhn-Logik.
  domain: automation
  input:
    climate_entity:
      name: Klimaanlage/Heizung
      selector:
        entity:
          domain: climate
    temp_sensor_entity:
      name: Temperatursensor (Ist-Temperatur)
      selector:
        entity:
          domain: sensor
    wunsch_temp_entity:
      name: Wunschtemperatur (Input-Helper)
      selector:
        entity:
          domain: input_number
    korrektur_faktor:
      name: Korrekturfaktor (Offset)
      default: 1.5
      selector:
        number:
          min: 0.0
          max: 10.0
          step: 0.5
          unit_of_measurement: "°C"
          mode: box
    window_sensor_entity:
      name: Fenster-/Türsensor (Optional)
      selector:
        entity:
          domain: binary_sensor
      default: []

trigger:
  - platform: state
    entity_id: !input temp_sensor_entity
  - platform: state
    entity_id: !input wunsch_temp_entity

action:
  - variables:
      # Alle Inputs als Variablen definieren, damit sie im Code verfügbar sind
      climate_ent: !input climate_entity
      temp_sensor_id: !input temp_sensor_entity
      wunsch_temp_id: !input wunsch_temp_entity
      window_sensor_id: !input window_sensor_entity
      offset: !input korrektur_faktor
      
      # Werte auslesen
      wunsch_temp: "{{ states(wunsch_temp_id) | float(0) }}"
      ist_temp: "{{ states(temp_sensor_id) | float(0) }}"
      
      # Solltemp berechnen
      berechnete_solltemp: "{{ (wunsch_temp + offset) | round(1) }}"
      
      # Föhn-Logik
      fan_to_use: >
        {% if ist_temp < wunsch_temp %}
          High
        {% elif ist_temp >= wunsch_temp and ist_temp <= (wunsch_temp + 0.5) %}
          MidHigh
        {% else %}
          Mid
        {% endif %}

  # 1. Prüfung: Fenster offen?
  - if:
      - condition: template
        value_template: "{{ is_state(window_sensor_id, 'on') if window_sensor_id != [] else false }}"
    then:
      - stop: "Fenster offen, Automatisierung gestoppt."

  # 2. Prüfung: Sind die Temperaturen gültige Zahlen?
  - condition: template
    value_template: "{{ states(wunsch_temp_id) | is_number and states(temp_sensor_id) | is_number }}"

  # 3. Klima einstellen
  - service: climate.set_temperature
    target:
      entity_id: "{{ climate_ent }}"
    data:
      temperature: "{{ berechnete_solltemp }}"
      hvac_mode: heat

  - service: climate.set_fan_mode
    target:
      entity_id: "{{ climate_ent }}"
    data:
      fan_mode: "{{ fan_to_use }}"
