blueprint:
  name: Klimaanlage - Föhn-Steuerung Final (Fixed)
  description: Fixer Offset zur Wunschtemp und 3-stufige Föhn-Logik.
  domain: automation
  input:
    climate_entity:
      name: Klimaanlage/Heizung
      selector:
        entity:
          domain: climate
    temp_sensor_entity:
      name: Temperatursensor (Ist-Temperatur)
      selector:
        entity:
          domain: sensor
    wunsch_temp_entity:
      name: Wunschtemperatur (Input-Helper)
      selector:
        entity:
          domain: input_number
    korrektur_faktor:
      name: Korrekturfaktor (Offset)
      default: 1.5
      selector:
        number:
          min: 0.0
          max: 10.0
          step: 0.5
          unit_of_measurement: "°C"
          mode: box

trigger:
  - platform: state
    entity_id: !input temp_sensor_entity
  - platform: state
    entity_id: !input wunsch_temp_entity

action:
  - variables:
      # Hier binden wir die Inputs korrekt an die Variablen
      wunsch_temp_id: !input wunsch_temp_entity
      temp_sensor_id: !input temp_sensor_entity
      climate_ent: !input climate_entity
      offset: !input korrektur_faktor
      
      # Jetzt berechnen wir die Werte basierend auf den IDs
      wunsch_temp: "{{ states(wunsch_temp_id) | float(0) }}"
      ist_temp: "{{ states(temp_sensor_id) | float(0) }}"
      
      berechnete_solltemp: "{{ (wunsch_temp + offset) | round(1) }}"
      
      fan_to_use: >
        {% if ist_temp < wunsch_temp %}
          High
        {% elif ist_temp >= wunsch_temp and ist_temp <= (wunsch_temp + 0.5) %}
          MidHigh
        {% else %}
          Mid
        {% endif %}

  # Erst prüfen, ob Werte gültig sind, dann ausführen
  - condition: template
    value_template: "{{ states(wunsch_temp_id) | is_number and states(temp_sensor_id) | is_number }}"

  - service: climate.set_temperature
    target:
      entity_id: "{{ climate_ent }}"
    data:
      temperature: "{{ berechnete_solltemp }}"
      hvac_mode: heat

  - service: climate.set_fan_mode
    target:
      entity_id: "{{ climate_ent }}"
    data:
      fan_mode: "{{ fan_to_use }}"
