blueprint:
  name: Wiederverwendbarer Heizungsregler (Delta)
  description: Passt die Soll-Temperatur einer Klimaanlage/Heizung dynamisch basierend auf einem externen Temperatursensor an.
  domain: automation
  input:
    # 1. Parameter: Die Klimaanlagen-Entität
    climate_entity:
      name: Klimaanlage/Heizung
      description: Die Entität (z.B. climate.schlafi_c931), deren Temperatur geregelt wird.
      selector:
        entity:
          domain: climate
    # 2. Parameter: Der Temperatursensor
    temp_sensor_entity:
      name: Temperatursensor (Ist-Temperatur)
      description: Der externe Temperatursensor (z.B. sensor.lumi_temperatur).
      selector:
        entity:
          domain: sensor
          device_class: temperature
    # 3. Parameter: Die Wunschtemperatur (Ihr input_number)
    wunsch_temp_entity:
      name: Wunschtemperatur (Input-Helper)
      description: Der input_number-Helfer, der die gewünschte Temperatur speichert.
      selector:
        entity:
          domain: input_number

trigger:
  # Triggert bei Änderung des externen Sensors
  - platform: state
    entity_id: !input temp_sensor_entity
  # Triggert bei Änderung der Wunschtemperatur
  - platform: state
    entity_id: !input wunsch_temp_entity

condition:
  # Die Fenster-Bedingung bleibt fest, da sie geräte-/raumabhängig ist.
  - type: is_not_open
    condition: device
    device_id: 40d8a228fa30cd06a40a19e69dde37da
    entity_id: 80b47c7dd6f3f65957d2d4eec1e4fca9
    domain: binary_sensor

action:
  - variables:
      # Variablen verwenden nun die Blueprint-Inputs
      wunsch_temp: "{{ states(!input wunsch_temp_entity) | float(0) }}"
      ist_temp: "{{ states(!input temp_sensor_entity) | float(0) }}"
      climate_ent: !input climate_entity # Vereinfachung für Aktionen
      max_solltemp: 30
      delta_fuer_heizen: "{{ (wunsch_temp - ist_temp) * 3 }}"
      neue_solltemp_heizen: >
        {% set ungefilterte_solltemp = wunsch_temp + delta_fuer_heizen %} {% set
        temp_mal_zwei = ungefilterte_solltemp * 2 %} {% set aufgerundet =
        temp_mal_zwei | round(0, 'ceil') %} {% set gerundet_final = aufgerundet
        / 2 %} {{ [max_solltemp, gerundet_final] | min | round(1) }}
      aktuelle_solltemp: "{{ state_attr(climate_ent, 'temperature') | float(0) }}"

  - choose:
      # Bedingung 1: Solltemperatur um 0.5 erhöhen
      - conditions:
          - condition: template
            value_template: "{{ ist_temp > (wunsch_temp - 0.25) }}"
          - condition: template
            value_template: "{{ (aktuelle_solltemp + 0.5) <= max_solltemp }}"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: '{{ climate_ent }}'
            data:
              temperature: "{{ (aktuelle_solltemp + 0.5) | round(1) }}"
              hvac_mode: heat
      # Bedingung 2: In Lüftermodus wechseln
      - conditions:
          - condition: template
            value_template: "{{ ist_temp > (wunsch_temp + 0.25) }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: '{{ climate_ent }}'
            data:
              hvac_mode: fan_only
          - service: climate.set_fan_mode
            target:
              entity_id: '{{ climate_ent }}'
            data:
              fan_mode: Low
    default:
      # Standard-Heizlogik
      - service: climate.set_hvac_mode
        target:
          entity_id: '{{ climate_ent }}'
        data:
          hvac_mode: heat
      - service: climate.set_temperature
        target:
          entity_id: '{{ climate_ent }}'
        data:
          temperature: "{{ neue_solltemp_heizen }}"
          hvac_mode: heat
      - service: climate.set_fan_mode
        target:
          entity_id: '{{ climate_ent }}'
        data:
          fan_mode: Mid
