blueprint:
  name: Klimaanlage - Föhn-Steuerung (Final Fix)
  description: Fixer Offset zur Wunschtemp und 3-stufige Föhn-Logik.
  domain: automation
  input:
    climate_entity:
      name: Klimaanlage/Heizung
      selector:
        entity:
          domain: climate
    temp_sensor_entity:
      name: Temperatursensor (Ist-Temperatur)
      selector:
        entity:
          domain: sensor
    wunsch_temp_entity:
      name: Wunschtemperatur (Input-Helper)
      selector:
        entity:
          domain: input_number
    korrektur_faktor:
      name: Korrekturfaktor (Offset)
      default: 1.5
      selector:
        number:
          min: 0.0
          max: 10.0
          step: 0.5
          unit_of_measurement: "°C"
          mode: box
    window_sensor_entity:
      name: Fenster-/Türsensor (Optional)
      selector:
        entity:
          domain: binary_sensor
      default: []

trigger:
  - platform: state
    entity_id: !input temp_sensor_entity
  - platform: state
    entity_id: !input wunsch_temp_entity

action:
  - variables:
      # Wir nutzen die !input direkt in den Variablen
      climate_ent: !input climate_entity
      temp_sensor_id: !input temp_sensor_entity
      wunsch_temp_id: !input wunsch_temp_entity
      window_sensor_id: !input window_sensor_entity
      offset_val: !input korrektur_faktor

  # 1. Prüfung: Fenster offen? (Nur wenn ein Sensor gewählt wurde)
  - if:
      - condition: template
        value_template: >
          {% if window_sensor_id != none and window_sensor_id != [] and states(window_sensor_id) != 'unknown' %}
            {{ is_state(window_sensor_id, 'on') }}
          {% else %}
            false
          {% endif %}
    then:
      - stop: "Fenster offen oder Sensor nicht verfügbar."

  # 2. Werte berechnen
  - variables:
      wunsch_temp: "{{ states(wunsch_temp_id) | float(0) }}"
      ist_temp: "{{ states(temp_sensor_id) | float(0) }}"
      berechnete_solltemp: "{{ (states(wunsch_temp_id) | float(0) + offset_val | float(0)) | round(1) }}"
      fan_to_use: >
        {% set ist = states(temp_sensor_id) | float(0) %}
        {% set wunsch = states(wunsch_temp_id) | float(0) %}
        {% if ist < wunsch %}
          High
        {% elif ist >= wunsch and ist <= (wunsch + 0.5) %}
          HighMid
        {% else %}
          Mid
        {% endif %}

  # 3. Klima einstellen
  - service: climate.set_temperature
    target:
      entity_id: "{{ climate_ent }}"
    data:
      # Wir nutzen hier > um sicherzustellen, dass es als Template-String interpretiert wird
      temperature: >
        {{ berechnete_solltemp }}
      hvac_mode: heat

  - service: climate.set_fan_mode
    target:
      entity_id: "{{ climate_ent }}"
    data:
      fan_mode: >
        {{ fan_to_use }}
