blueprint:
  name: Klimaanlage - Dynamische Temperaturanpassung (Faktor)
  description: Passt die Soll-Temperatur einer Klimaanlage/Heizung dynamisch basierend auf einem externen Temperatursensor an. Nutzt einen einstellbaren Korrekturfaktor.
  domain: automation
  input:
    climate_entity:
      name: Klimaanlage/Heizung
      description: Die Entität (z.B. climate.schlafi_c931), deren Temperatur geregelt wird.
      selector:
        entity:
          domain: climate
    temp_sensor_entity:
      name: Temperatursensor (Ist-Temperatur)
      description: Der externe Temperatursensor (z.B. sensor.lumi_temperatur).
      selector:
        entity:
          domain: sensor
    wunsch_temp_entity:
      name: Wunschtemperatur (Input-Helper)
      description: Der input_number-Helfer, der die gewünschte Temperatur speichert.
      selector:
        entity:
          domain: input_number
    korrektur_faktor:
      name: Korrekturfaktor (z.B. 3.0)
      description: Multiplikator für die Temperaturdifferenz (Diff x Faktor). Höherer Wert = aggressiveres Heizen.
      default: 3.0
      selector:
        number:
          min: 1.0
          max: 10.0
          unit_of_measurement: "Faktor"
          mode: box
    window_sensor_entity:
      name: Fenster-/Türsensor (Lüftungsprüfung)
      description: Optionaler Sensor, der prüft, ob gelüftet wird. Automatisierung stoppt, wenn Sensor offen ist (state 'on'). Leer lassen, um die Prüfung zu ignorieren.
      selector:
        entity:
          domain: binary_sensor
      default: ''

trigger:
  - platform: state
    entity_id: !input temp_sensor_entity
  - platform: state
    entity_id: !input wunsch_temp_entity

condition:
  - condition: template
    value_template: >
      {# Prüft, ob der optionale Sensor nicht existiert ODER 'off' ist #}
      {% if is_state('!input window_sensor_entity', 'off') %}
        True
      {% elif '!input window_sensor_entity' == 'null' or '!input window_sensor_entity' == '' or 'window_sensor_entity' not in states %}
        True
      {% else %}
        False
      {% endif %}
    alias: "Prüfen, ob Fenster/Tür geschlossen ist (optional)"

action:
  - variables:
      # Zuweisung der Input-Entitäten
      climate_ent: !input climate_entity
      temp_sensor_ent: !input temp_sensor_entity
      wunsch_temp_ent: !input wunsch_temp_entity
      
      # Abrufen des Korrekturfaktors aus dem Input-Feld
      faktor: !input korrektur_faktor
      
      # Abrufen der Ist- und Wunschtemperatur
      wunsch_temp: "{{ states(wunsch_temp_ent) | float(0) }}"
      ist_temp: "{{ states(temp_sensor_ent) | float(0) }}"
      
      max_solltemp: 30
      temp_diff: "{{ wunsch_temp - ist_temp }}"
      
      # LOGIK: Diff * Korrekturfaktor, mit 0.5 Boost im Nahbereich
      delta_fuer_heizen: >
        {% set raw_delta = temp_diff * faktor %}
        
        {# Fall 1: Aggressiver Boost (0 < Diff <= 0.5) -> Multiplikation + 0.5 Schub #}
        {% if temp_diff > 0 and temp_diff <= 0.5 %}
            {{ (raw_delta + 0.5) | round(1) }}
        
        {# Fall 2: Stark Heizen (Diff > 0.5) -> Nur Multiplikation #}
        {% elif temp_diff > 0.5 %}
            {{ raw_delta | round(1) }}

        {# Fall 3: Halten/Abkühlen im Nahbereich (Negatives Delta, aber Ist < Wunsch + 0.5) -> Limit auf min. -1.0 #}
        {% elif raw_delta < 0 and ist_temp < (wunsch_temp + 0.5) %}
          {{ [raw_delta, -1.0] | max | round(1) }}
          
        {# Fall 4: Starkes Abkühlen/Gleich Null #}
        {% else %}
          {{ raw_delta | round(1) }}
        {% endif %}
          
      # Berechnet die neue Solltemperatur und rundet sie auf die nächste 0.5er Stufe
      neue_solltemp_heizen: >
        {% set ungefilterte_solltemp = wunsch_temp + delta_fuer_heizen %} {% set
        temp_mal_zwei = ungefilterte_solltemp * 2 %} {% set aufgerundet =
        temp_mal_zwei | round(0, 'ceil') %} {% set gerundet_final = aufgerundet
        / 2 %} {{ [max_solltemp, gerundet_final] | min | round(1) }}
        
      aktuelle_solltemp: "{{ state_attr(climate_ent, 'temperature') | float(0) }}"

  - choose:
      # ZONE 1: LÜFTERMODUS (Ist >= Wunsch + 0.25)
      - conditions:
          - condition: template
            value_template: "{{ ist_temp >= (wunsch_temp + 0.25) }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: '{{ climate_ent }}'
            data:
              hvac_mode: fan_only
          - service: climate.set_fan_mode
            target:
              entity_id: '{{ climate_ent }}'
            data:
              fan_mode: Low
              
    default:
      # Alle anderen Zustände (Heizen oder Halten) greifen hier
      - service: climate.set_hvac_mode
        target:
          entity_id: '{{ climate_ent }}'
        data:
          hvac_mode: heat
      - service: climate.set_temperature
        target:
          entity_id: '{{ climate_ent }}'
        data:
          temperature: "{{ neue_solltemp_heizen }}"
          hvac_mode: heat
      - service: climate.set_fan_mode
        target:
          entity_id: '{{ climate_ent }}'
        data:
          fan_mode: Mid
