blueprint:
  name: Klimaanlage - Dynamische Temperaturanpassung
  description: Passt die Soll-Temperatur einer Klimaanlage/Heizung dynamisch basierend auf einem externen Temperatursensor an.
  domain: automation
  input:
    climate_entity:
      name: Klimaanlage/Heizung
      description: Die Entität (z.B. climate.schlafi_c931), deren Temperatur geregelt wird.
      selector:
        entity:
          domain: climate
    temp_sensor_entity:
      name: Temperatursensor (Ist-Temperatur)
      description: Der externe Temperatursensor (z.B. sensor.lumi_temperatur).
      selector:
        entity:
          domain: sensor
          device_class: temperature
    wunsch_temp_entity:
      name: Wunschtemperatur (Input-Helper)
      description: Der input_number-Helfer, der die gewünschte Temperatur speichert.
      selector:
        entity:
          domain: input_number
    window_sensor_entity:
      name: Fenster-/Türsensor (Lüftungsprüfung)
      description: Optionaler Sensor, der prüft, ob gelüftet wird. Automatisierung stoppt, wenn Sensor offen ist (state 'on'). Leer lassen, um die Prüfung zu ignorieren.
      selector:
        entity:
          domain: binary_sensor
          device_class: window
      default: ''

trigger:
  - platform: state
    entity_id: !input temp_sensor_entity
  - platform: state
    entity_id: !input wunsch_temp_entity

condition:
  - condition: template
    value_template: |
      {% set sensor = iinput('window_sensor_entity') %}
      {% if sensor is none or sensor == '' %}
        True
      {% else %}
        {{ is_state(sensor, 'off') }}
      {% endif %}
    alias: "Prüfen, ob Fenster/Tür geschlossen ist (optional)"

action:
  - variables:
      climate_ent: !input climate_entity
      temp_sensor_ent: !input temp_sensor_entity
      wunsch_temp_ent: !input wunsch_temp_entity
      
      wunsch_temp: "{{ states(wunsch_temp_ent) | float(0) }}"
      ist_temp: "{{ states(temp_sensor_ent) | float(0) }}"
      
      max_solltemp: 30
      delta_fuer_heizen: "{{ (wunsch_temp - ist_temp) * 3 }}"
      neue_solltemp_heizen: >
        {% set ungefilterte_solltemp = wunsch_temp + delta_fuer_heizen %} {% set
        temp_mal_zwei = ungefilterte_solltemp * 2 %} {% set aufgerundet =
        temp_mal_zwei | round(0, 'ceil') %} {% set gerundet_final = aufgerundet
        / 2 %} {{ [max_solltemp, gerundet_final] | min | round(1) }}
      aktuelle_solltemp: "{{ state_attr(climate_ent, 'temperature') | float(0) }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ ist_temp > (wunsch_temp - 0.25) }}"
          - condition: template
            value_template: "{{ (aktuelle_solltemp + 0.5) <= max_solltemp }}"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: '{{ climate_ent }}'
            data:
              temperature: "{{ (aktuelle_solltemp + 0.5) | round(1) }}"
              hvac_mode: heat
      - conditions:
          - condition: template
            value_template: "{{ ist_temp > (wunsch_temp + 0.25) }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: '{{ climate_ent }}'
            data:
              hvac_mode: fan_only
          - service: climate.set_fan_mode
            target:
              entity_id: '{{ climate_ent }}'
            data:
              fan_mode: Low
    default:
      - service: climate.set_hvac_mode
        target:
          entity_id: '{{ climate_ent }}'
        data:
          hvac_mode: heat
      - service: climate.set_temperature
        target:
          entity_id: '{{ climate_ent }}'
        data:
          temperature: "{{ neue_solltemp_heizen }}"
          hvac_mode: heat
      - service: climate.set_fan_mode
        target:
          entity_id: '{{ climate_ent }}'
        data:
          fan_mode: Mid
