blueprint:
  name: Klimaanlage - Dynamischer Föhn & Variabler Offset
  description: Setzt Solltemp auf Wunschtemp + Korrekturfaktor und regelt den Föhn stufenweise.
  domain: automation
  input:
    climate_entity:
      name: Klimaanlage/Heizung
      selector:
        entity:
          domain: climate
    temp_sensor_entity:
      name: Temperatursensor (Ist-Temperatur)
      selector:
        entity:
          domain: sensor
    wunsch_temp_entity:
      name: Wunschtemperatur (Input-Helper)
      selector:
        entity:
          domain: input_number
    korrektur_faktor:
      name: Korrekturfaktor (Offset)
      description: Dieser Wert wird auf die Wunschtemperatur addiert, um die Solltemperatur der Klima zu setzen.
      default: 1.5
      selector:
        number:
          min: 0.0
          max: 5.0
          step: 0.5
          unit_of_measurement: "°C"
          mode: box
    window_sensor_entity:
      name: Fenster-/Türsensor (Optional)
      selector:
        entity:
          domain: binary_sensor
      default: []

trigger:
  - platform: state
    entity_id: !input temp_sensor_entity
  - platform: state
    entity_id: !input wunsch_temp_entity

action:
  - if:
      - condition: template
        value_template: "{{ is_state(window_sensor_entity, 'on') if window_sensor_entity != [] else false }}"
    then:
      - stop: "Fenster offen."

  - variables:
      climate_ent: !input climate_entity
      wunsch_temp: "{{ states(wunsch_temp_entity) | float(0) }}"
      ist_temp: "{{ states(temp_sensor_entity) | float(0) }}"
      offset: !input korrektur_faktor
      
      # Solltemperatur = Wunsch + variabler Korrekturfaktor
      berechnete_solltemp: "{{ (wunsch_temp + offset) | round(1) }}"
      
      # Föhn-Logik nach deinen Vorgaben
      fan_to_use: >
        {% if ist_temp < wunsch_temp %}
          High
        {% elif ist_temp >= wunsch_temp and ist_temp <= (wunsch_temp + 0.5) %}
          MidHigh
        {% else %}
          Mid
        {% endif %}

  - service: climate.set_temperature
    target:
      entity_id: "{{ climate_ent }}"
    data:
      temperature: "{{ berechnete_solltemp }}"
      hvac_mode: heat

  - service: climate.set_fan_mode
    target:
      entity_id: "{{ climate_ent }}"
    data:
      fan_mode: "{{ fan_to_use }}"
