blueprint:
  name: Klimaanlage - Föhn-Steuerung
  description: Variabler Offset zur Wunschtemp und 3-stufige Föhn-Logik.
  domain: automation
  input:
    climate_entity:
      name: Klimaanlage/Heizung
      selector:
        entity:
          domain: climate
    temp_sensor_entity:
      name: Temperatursensor (Ist-Temperatur)
      selector:
        entity:
          domain: sensor
    wunsch_temp_entity:
      name: Wunschtemperatur (Input-Helper)
      selector:
        entity:
          domain: input_number
    korrektur_faktor:
      name: Korrekturfaktor (Offset)
      default: 1.5
      selector:
        number:
          min: 0.0
          max: 10.0
          step: 0.5
          unit_of_measurement: "°C"
          mode: box
    window_sensor_entity:
      name: Fenster-/Türsensor (Optional)
      selector:
        entity:
          domain: binary_sensor
      default: []

trigger:
  - platform: state
    entity_id: !input temp_sensor_entity
  - platform: state
    entity_id: !input wunsch_temp_entity

action:
  - variables:
      # Hier werden die Inputs als interne Variablen deklariert
      climate_ent: !input climate_entity
      temp_sensor_id: !input temp_sensor_entity
      wunsch_temp_id: !input wunsch_temp_entity
      window_sensor_id: !input window_sensor_entity
      offset: !input korrektur_faktor
      
      # Berechnung der Werte
      wunsch_temp: "{{ states(wunsch_temp_id) | float(0) }}"
      ist_temp: "{{ states(temp_sensor_id) | float(0) }}"
      berechnete_solltemp: "{{ (wunsch_temp + offset) | round(1) }}"
      
      # Föhn-Logik (Stufe 4, 3, 2)
      fan_to_use: >
        {% if ist_temp < wunsch_temp %}
          High
        {% elif ist_temp >= wunsch_temp and ist_temp <= (wunsch_temp + 0.5) %}
          MidHigh
        {% else %}
          Mid
        {% endif %}

  # Prüfung: Fenster offen? (Nutzt jetzt die Variable window_sensor_id)
  - if:
      - condition: template
        value_template: "{{ is_state(window_sensor_id, 'on') if window_sensor_id != [] else false }}"
    then:
      - stop: "Fenster offen."

  # Prüfung: Sind Zahlen vorhanden?
  - condition: template
    value_template: "{{ states(wunsch_temp_id) | is_number and states(temp_sensor_id) | is_number }}"

  # Ausführung
  - service: climate.set_temperature
    target:
      entity_id: "{{ climate_ent }}"
    data:
      temperature: "{{ berechnete_solltemp }}"
      hvac_mode: heat

  - service: climate.set_fan_mode
    target:
      entity_id: "{{ climate_ent }}"
    data:
      fan_mode: "{{ fan_to_use }}"
