blueprint:
  name: Klimaanlage - Föhn Steuerung
  description: Dynamische Lüftersteuerung und fixer Temperatur-Offset.
  domain: automation
  input:
    climate_entity:
      name: Klimaanlage
      selector:
        entity:
          domain: climate
    temp_sensor_entity:
      name: Ist-Temperatur Sensor
      selector:
        entity:
          domain: sensor
    wunsch_temp_entity:
      name: Wunschtemperatur (Helper)
      selector:
        entity:
          domain: input_number
    korrektur_faktor:
      name: Korrekturfaktor
      default: 1.5
      selector:
        number:
          min: 0.0
          max: 10.0
          step: 0.5
          unit_of_measurement: "°C"
          mode: box

trigger:
  - platform: state
    entity_id: !input temp_sensor_entity
  - platform: state
    entity_id: !input wunsch_temp_entity

action:
  # 1. Abbruch wenn Fenster offen (falls eins ausgewählt wurde)

  # 2. Temperatur setzen (Offset wird direkt hier berechnet)
  - service: climate.set_temperature
    target:
      entity_id: !input climate_entity
    data:
      hvac_mode: heat
      temperature: >
        {% set wunsch = states('!input wunsch_temp_entity') | float(21) %}
        {% set offset = !input korrektur_faktor %}
        {{ (wunsch + offset) | round(1) }}

  # 3. Lüfterstufe setzen (Logik direkt im Service)
  - service: climate.set_fan_mode
    target:
      entity_id: !input climate_entity
    data:
      fan_mode: >
        {% set ist = states('!input temp_sensor_entity') | float(0) %}
        {% set wunsch = states('!input wunsch_temp_entity') | float(0) %}
        {% if ist < wunsch %}
          High
        {% elif ist >= wunsch and ist <= (wunsch + 0.5) %}
          MidHigh
        {% else %}
          Mid
        {% endif %}